import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { Roboto } from 'next/font/google'

import '@/app/styles/globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang='en'>
    <body
      className={`${roboto.variable} tablet:text-md bg-black text-base
        font-normal text-white antialiased`}>
      <main>{children}</main>
    </body>
  </html>
)
