name: Code Quality & Standards Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Installing dependencies
        run: bun i

      - name: Run Linter
        run: bun lint

      - name: Verify Code Formatting
        run: bun format:check

      - name: Enforce Conventional Commits
        uses: webiny/action-conventional-commits@v1.1.0
